- name: Check if upstart config file exists or not
  stat: path=/etc/init/{{ upstart.config_name }}
  register: upstart_path

- name: Stopping "{{ upstart.service_name }}" service
  service: name="{{ upstart.service_name }}" state=stopped
  when: upstart_path.stat.exists == True
  
- name: Reset cached folders
  file:
    path={{ dir }}/{{ cache_dir }}/
    state=absent

- name: Get a codebase for service
  git: repo=git@bitbucket.org:avaea_eng/avaea.git
    dest="{{ dir }}"
    version="{{ GIT_BRANCH }}"
    update=yes
    accept_hostkey=yes
    force=yes
    ssh_opts="-o StrictHostKeyChecking=no"
    key_file=/root/.ssh/bitbucket_rsa

- name: Delete if exists nginx defualt config
  file:
   path=/etc/nginx/sites-enabled/default
   state=absent

- name: Deploy nginx configs
  template: src=configs/nginx/sites-enabled/{{ APP }}
    dest=/etc/nginx/sites-enabled/{{ nginx.config_name }}
    owner=root
    group=root
    mode=0644

- name: Copy upstart configs
  template:
    src=configs/upstart/{{ APP }}.conf
    dest=/etc/init/{{ upstart.config_name }}
    owner=root
    group=root
    mode=0644

- name: Restart "{{ upstart.service_name }}" service
  service: name="{{ upstart.service_name }}" state=started

- name: Restart nginx service
  service: name=nginx state=restarted