image: node:5.11.0
pipelines:
  default:
    - step:
        script:
          - echo "This script runs on all branches that don't have any specific pipeline assigned in 'branches'."
  branches:
    DEMO-806*:
      - step:
          script:
            - pwd
            - cd src
            - npm install
            - make test-unit