#image: node:5.11.0
image: spittet/node-postgresql
pipelines:
  default:
    - step:
        script:
          - echo "This script runs on all branches that don't have any specific pipeline assigned in 'branches'."
  branches:
    DEMO-806*:
      - step:
          script:
            #- apt update
            #- apt-get -y install net-tools
             - /etc/init.d/postgresql start
             - sudo -u postgres sh -c 'createuser avaea & createdb avaea_db' # creating a root user 
             - sudo -u postgres psql -c "ALTER USER root PASSWORD 'avaea';" # setting up the root password
             - sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE avaea_db to avaea;" 
             - npm install pg
#             - PGPASSWORD=
             - sudo -u postgres sh -c 'psql -d avaea_db  < avaea.sql'
             - pwd
            #- ping -c 3 kernel.org
            #- ps aux
            #- node -v
            #- psql -V
            #- netstat -anp
            #- /sbin/ifconfig
            #- df -h
 #           - cd src
 #           - npm install
 #           - make test-unit