image: node:5.11.0

pipelines:
 default:
  - step:
     script:
         echo default script
     
 branches:
  DEMO-806*:
  - step:
      script:
     - cd src
     - npm install
     - export NODE_ENV="staging"
     - export GOOGLE_OAUTH_CLIENT_ID="353849264959-s6n15fmj0s094hs95b46s5osuikm2agi.apps.googleusercontent.com"
     - export GOOGLE_OAUTH_CLIENT_SECRET="wURGldrAW0CS1kS8PX1QJi1m" 
     - make test-unit
     - make test-integration