image: avaea/demo
pipelines:
  default:
    - step:
        script:
          - echo "This script runs on all branches that don't have any specific pipeline assigned in 'branches'."
  branches:
    RC_20161205:
      - step:
          script:
              - /etc/init.d/postgresql start
             # - sleep 180
              - cd src
              - mv /node_modules .
              - npm install
              - export NODE_ENV="staging"
              - export GOOGLE_OAUTH_CLIENT_ID="353849264959-s6n15fmj0s094hs95b46s5osuikm2agi.apps.googleusercontent.com"
              - export GOOGLE_OAUTH_CLIENT_SECRET="wURGldrAW0CS1kS8PX1QJi1m" 
              - make test-unit
              -  ./node_modules/.bin/jest
              #- make test-integration