version: '2'
services:
  sources:
    image: ubuntu:14.04
    volumes:
      - .:/usr/var/avaea
    networks:
      - avaea_network
    command: bash -c "sleep infinity"

  avaea:
    extends:
      file: images/node/node_base.yml
      service: nodebase
    volumes_from:
      - sources
    networks:
      - avaea_network
    working_dir: /usr/var/avaea/src
    command: bash -c "/usr/local/bin/run_avaea.sh"
    environment:
      NODE_PATH: "/usr/var/avaea/src/node_modules"
      NODE_ENV: "docker"
      PROXY_PORT: "81"
    ports:
      - "8001:8000"

  abo:
    extends:
      file: images/node/node_base.yml
      service: nodebase
    volumes_from:
      - sources
    networks:
      - avaea_network
    working_dir: /usr/var/avaea/abo
    command: bash -c "/usr/local/bin/run_abo.sh"
    environment:
      NODE_PATH: "/usr/var/avaea/abo/node_modules"
      NODE_ENV: "docker"
      PROXY_PORT: "81"
    ports:
      - "8081:8080"

  nginx:
    build:
      context: .
      dockerfile: ./images/nginx/nginx.Dockerfile
    privileged: True
    networks:
      - avaea_network
    depends_on:
      - avaea
      - abo
    volumes_from:
      - sources
    ports:
      - "81:80"
      - "23457:23457"
      - "8022:22"
    command: bash -c "/usr/local/bin/setup_and_run.sh"

  cache:
    image: memcached
    networks:
      - avaea_network
    ports:
      - "11212:11211"


  postgres:
    build:
      context: .
      dockerfile: images/postgres/postgres.Dockerfile
    networks:
      - avaea_network
    ports:
      - "5433:5432"

networks:
  avaea_network:
    driver: bridge
