dir: /root/demo

nginx:
  listen_host: avaea
  listen_port: 80
  server_name: avaea.com www.avaea.com
  proxy_pass_host: localhost
  proxy_pass_port: 8000
  config_name: demo.conf
  source_name: demo

upstart:
  config_name: demo.conf
  service_name: demo
  log_name: demo.log

cache_dir: src/.tmp/public

node_env: production