dir: /root/demo

nginx:
  listen_host: avaea
  listen_port: 80
  server_name: demotest.avaea.com
  proxy_pass_host: localhost
  proxy_pass_port: 8000
  config_name: demo.conf

upstart:
  config_name: demo.conf
  service_name: demo

cache_dir: src/.tmp/public