---

- name: make sure local keys directory exists
  local_action:
    module: file
    state: directory
    path: "{{ playbook_dir }}/keys"

- name: remove existing keypair when force_keypair=True
  local_action:
    module: ec2_key
    name: "{{ name|default('tutorial') }}"
    region: "{{ region|default('us-west-2') }}"
    state: absent
  when: force_keypair|default(False)

- name: make a keypair with the specified name
  local_action:
    module: ec2_key
    name: "{{ name|default('tutorial') }}"
    region: "{{ region|default('us-west-2') }}"
    wait: yes
  register: key_data

- name: save the key file to local host
  local_action:
    module: copy
    content: "{{ key_data.key.private_key }}"
    dest: "keys/{{ name|default('tutorial') }}"
    mode: 0600
  when: key_data.key.private_key|default(0)

- name: debug keypair
  debug: msg="{{ key_data }}"
