- name: set hostname to host
  hostname: name={{ hostname }}

- name: Deploy a bitbucket key
  copy: src=vars/production/bitbucket_rsa
    dest=/root/.ssh/bitbucket_rsa
    owner=root
    group=root
    mode=0400

- name: install node
  shell: curl -sL https://deb.nodesource.com/setup_4.x | bash -

- name: installing some dependencies
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
  - git
  - build-essential
  - nodejs
  - python-pip

- name: installing python dependencies
  pip: name=boto

- name: Copy db dump
  copy: src=../../images/postgres/data/avaea.sql.gz
    dest=/tmp
    owner=root
    group=root
    mode=0644
  when: artifact_source is not defined

- name: Copy db dump from s3 bucket
  s3: bucket=avaeadbpostgres
    aws_access_key="{{ lookup('env','AWS_ACCESS_KEY') }}"
    aws_secret_key="{{ lookup('env','AWS_SECRET_KEY') }}"
    region="{{ lookup('env','AWS_DEFAULT_REGION') }}"
    object=/avaea.sql.gz
    dest=/tmp/avaea.sql.gz
    mode=get
  when: artifact_source is defined and artifact_source == 's3'

- name: Upload sql dump to db
  shell: gunzip -c /tmp/avaea.sql.gz | psql -U postgres

