- name: Stopping "{{ upstart.service_name }}" service
  service: name="{{ upstart.service_name }}" state=stopped

- name: Reset cached folders
  file:
    path={{ dir }}/{{ cache_dir }}/
    state=absent

- name: Update codebase
  git: repo=git@bitbucket.org:avaea_eng/avaea.git
    dest="{{ dir }}"
    version="{{ GIT_BRANCH }}"
    update=yes
    clone=no
    accept_hostkey=yes
    force=yes
    key_file=/root/.ssh/bitbucket_rsa

- name: Delete if exists nginx defualt config
  file:
   path=/etc/nginx/sites-enabled/default.conf
   state=absent

- name: Deploy nginx configs
  template: src=configs/nginx/sites-enabled/{{ APP }}
    dest=/etc/nginx/sites-enabled/{{ nginx.config_name }}
    owner=root
    group=root
    mode=0644

- name: Copy upstart configs
  template:
    src=configs/upstart/{{ upstart.config_name }}
    dest=/etc/init/{{ upstart.config_name }}
    owner=root
    group=root
    mode=0644

- name: Restart "{{ upstart.service_name }}" service
  service: name="{{ upstart.service_name }}" state=started