- name: Deploy avaea application to stage server
  hosts: web.avaea
  gather_facts: false
  connection: ssh
  vars_files:
    - vars/{{ ENV }}/{{ APP }}
    - vars/{{ ENV }}/environment.yaml

  roles:
  - app
