- name: Deploy avaea application to stage server
  hosts: web.avaea
  gather_facts: false
  connection: ssh
  become: yes
  vars_files:
    - vars/{{ ENV }}/{{ APP }}
    - vars/{{ ENV }}/environment.yaml

  pre_tasks:
    - name: Update apt
      become: yes
      apt:
        cache_valid_time: 1800
        update_cache: yes
      tags:
        - build

  roles:
  - app
