- name: Wait for become yes
  hosts:
    - tag_Name_avaea1
  connection: ssh
  gather_facts: no
  remote_user: ubuntu
  tasks:
    - command: sleep "{{ item }}"
      become: yes
      with_items:
        - 1
        - 15

- name: Deploy avaea application to a production server
  hosts:
    - tag_Name_avaea1
  gather_facts: true
  connection: ssh
  remote_user: ubuntu
  become: yes
  vars_files:
    - vars/production/{{ APP }}.yaml
    - vars/production/environment.yaml

  roles:
  - production.nginx
  - app