- name: Deploy nginx configs for docker environment
  hosts: nginx.sandbox
  connection: local
  gather_facts: false
  vars_files:
    - vars/sandbox/{{ APP }}
    - vars/sandbox/environment.yaml

  roles:
  - sandbox.nginx