DROP TABLE if exists ffm_programs;

CREATE TABLE "ffm_programs" (
  id serial NOT NULL,
  program_code varchar,
  program_name varchar,
  help_url varchar,
  web_site_url varchar,
  signup_url varchar,
  alliance varchar,
  miles_type_configuration json,
  tiers_configuration json,
  airlines json,
  "createdAt" timestamp with time zone,
  "updatedAt" timestamp with time zone,
  CONSTRAINT ffm_programs_pkey PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);

ALTER TABLE "ffm_programs"
  OWNER TO avaea;

CREATE INDEX ON ffm_programs ((lower(program_code)));

INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('AAA', 'American Airlines AAdvantage', 'https://www.americanairlines.com/login/needPasswordAccess.do', '', 'https://www.americanairlines.com/loyalty/enrollment/enroll', 'OneWorld', '[{"at":"1","atn":"Award Miles"},{"at":"2","atn":"Elite Qualifying Miles"},{"at":"3","atn":"Elite Qualifying Segments"},{"at":"5","atn":"Elite Qualifying Dollars","med":"2017-01-01"}]', '[{"ta":"1","tn":"Member"},{"ta":"8","tn":"Gold"},{"ta":"16","tn":"Platinum"},{"ta":"24","tn":"Executive Platinum"}]', '["AA"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('ACA', 'Air Canada Altitude/Aeroplan', 'https://www3.aeroplan.com/recover/reset-password', '', 'https://www3.aeroplan.com/enroll.do', 'StarAlliance', '[{"at":"1","atn":"Aeroplan Miles"},{"at":"2","atn":"Altitude Qualifying Miles"},{"at":"3","atn":"Altitude Qualifying Segments"},{"at":"5","atn":"Altitude Qualifying Dollars"}]', '[{"ta":"1","tn":"Member"},{"ta":"8","tn":"Altitude Prestige 25K"},{"ta":"16","tn":"Altitude Elite 35K"},{"ta":"24","tn":"Altitude Elite 50K"},{"ta":"32","tn":"Altitude Elite 75K"},{"ta":"33","tn":"Altitude Super Elite 100K"}]', '["7F","AC","JV","MO","YN"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('ACP', 'Air China Phoenix Miles', 'http://ffp.airchina.com.cn/en/user/retrieve/gd2042a.jsp', '', 'http://ffp.airchina.com.cn/en/mainno.jsp?url=/en/user/gd2011a.jsp', 'StarAlliance', '[{"at":"1","atn":"Award miles"},{"at":"2","atn":"Status miles"},{"at":"3","atn":"Status segments"}]', '[{"ta":"1","tn":"Companion Card"},{"ta":"8","tn":"Silver"},{"ta":"16","tn":"Gold"},{"ta":"24","tn":"Platinum"},{"ta":"32","tn":"Lifetime Platinum"}]', '["CA","NX","SC","TV","ZH"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('AFL', 'Aeroflot Bonus', 'https://www.aeroflot.ru/personal/forgot_password?login=', '', 'https://www.aeroflot.ru/personal/login/?_preferredLanguage=en', 'SkyTeam', '[{"at":"1","atn":"Miles"},{"at":"2","atn":"Status Miles"},{"at":"3","atn":"Status Segments"}]', '[{"ta":"1","tn":"Basic Member"},{"ta":"8","tn":"Silver"},{"ta":"16","tn":"Gold"},{"ta":"24","tn":"Platinum"}]', '["D9","FV","HZ","R2","SU"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('AKB', 'AirAsia BIG Loyalty Programme', 'https://member.airasia.com/forgot-your-password.aspx', '', 'https://member.airasia.com/register.aspx?culture=en-GB', 'Independent', '[{"at":"1","atn":"BIG Points"}]', '[{"ta":"1","tn":"BIG Shot"}]', '["AK","D7","FD","I5","PQ","QZ","XJ","XT","Z2"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('AKF', 'Air France/KLM Flying Blue', 'https://www.klm.com/ams/account/secure/myProfileForm.htm#g_np_mya-overlay=1&mya-dl=/lightbox/forgotPasswordOrPincode.htm', '', 'https://www.flyingblue.com/join-flyingblue.html', 'SkyTeam', '[{"at":"1","atn":"Award Miles"},{"at":"2","atn":"Level Miles"},{"at":"3","atn":"Qualifying Flights"}]', '[{"ta":"1","tn":"Ivory"},{"ta":"8","tn":"Silver"},{"ta":"16","tn":"Gold"},{"ta":"24","tn":"Platinum"}]', '["A5","AF","HV","KL","KQ","RO","SB","TO"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('ALM', 'Avianca LifeMiles', 'https://www.lifemiles.com/eng/cus/cnt/cntgetpas.aspx', '', 'https://www.lifemiles.com/eng/mya/myp/mypfasenr.aspx', 'StarAlliance', '[{"at":"1","atn":"Award Miles"},{"at":"2","atn":"Qualifying Miles"},{"at":"3","atn":"Qualifying Segments"}]', '[{"ta":"1","tn":"LifeMiles"},{"ta":"8","tn":"Silver"},{"ta":"16","tn":"Gold"},{"ta":"24","tn":"Diamond"}]', '["2K","AV","LR","T0","TA"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('AMB', 'Aegean Airlines Miles&Bonus', 'https://en.aegeanair.com/member/forgot-password/', '', 'https://en.aegeanair.com/milesandbonus/member/enroll/', 'StarAlliance', '[{"at":"1","atn":"Award Miles"},{"at":"2","atn":"Tier Miles"}]', '[{"ta":"1","tn":"Blue"},{"ta":"8","tn":"Silver"},{"ta":"16","tn":"Gold"}]', '["A3","OA"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('AMC', 'ANA Mileage Club', 'https://cam.ana.co.jp/reminder/ReminderInputServlet_e', '', 'https://cam.ana.co.jp/amcmember/amcentry/AMCEntryFacadeEn', 'StarAlliance', '[{"at":"1","atn":"Miles"},{"at":"2","atn":"Premium Points"}]', '[{"ta":"1","tn":"Member"},{"ta":"8","tn":"Bronze"},{"ta":"16","tn":"Platinum"},{"ta":"24","tn":"Diamond"}]', '["NH"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('AMM', 'Alitalia MilleMiglia', 'https://www.alitalia.com/en_it/special-pages/recupera-pin.html', '', 'https://www.alitalia.com/en_it/special-pages/subscribe_mm_program.html', 'SkyTeam', '[{"at":"1","atn":"Miles"},{"at":"2","atn":"Qualifying Miles"},{"at":"3","atn":"Qualifying Flights"}]', '[{"ta":"1","tn":"Member"},{"ta":"8","tn":"Ulisse"},{"ta":"16","tn":"Freccia Alata Club"},{"ta":"24","tn":"Freccia Alata Plus Club"}]', '["AZ","CT"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('AMP', 'Alaska Airlines Mileage Plan', 'https://www.alaskaair.com/myaccount/forgotcredentials/password', '', 'https://www.alaskaair.com/myaccount/join?&LID=nav%3amileage-join', 'Independent', '[{"at":"1","atn":"Miles"},{"at":"2","atn":"Status miles"},{"at":"3","atn":"Status segments"}]', '[{"ta":"1","tn":"Member"},{"ta":"8","tn":"MVP"},{"ta":"16","tn":"MVP Gold"},{"ta":"24","tn":"MVP Gold 75K"}]', '["AS","QX"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('ARD', 'Air Arabia Airewards', 'https://reservations.airarabia.com/ibe/public/showCustomerLoadPage!loadCustomerForgotPWD.action', '', 'https://reservations.airarabia.com/ibe/public/showReservation.action?hdnParamData=EN^RE&hdnCarrier=G9', 'Independent', '[{"at":"1","atn":"Airewards Points"}]', '[{"ta":"1","tn":"Airewards Member"}]', '["3O","9P","E5","G9"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('ARP', ' Aerolíneas Plus', 'http://www.aerolineas.com.ar/en-ar/aerolineas_plus/my_plus_account/olvidastetuclave1', '', 'http://www.aerolineas.com.ar/en-ar/aerolineas_plus/my_plus_account/primeravez', 'SkyTeam', '[{"at":"1","atn":"Miles"},{"at":"2","atn":"Status miles"},{"at":"3","atn":"Status segments"}]', '[{"ta":"1","tn":"Classic"},{"ta":"8","tn":"Gold"},{"ta":"16","tn":"Platinum"}]', '["AR","AU"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('ASC', 'Asiana Club', 'http://eu.flyasiana.com/I/EN/SearchPW.do?paramValue=false', '', 'http://eu.flyasiana.com/I/en/MemberRegistrationMain.do', 'StarAlliance', '[{"at":"1","atn":"Award miles"},{"at":"2","atn":"Status miles"},{"at":"3","atn":"Status segments"}]', '[{"ta":"1","tn":"Silver"},{"ta":"8","tn":"Gold"},{"ta":"16","tn":"Diamond"},{"ta":"24","tn":"Diamond Plus"},{"ta":"32","tn":"Platinum"}]', '["OZ"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('BAC', 'British Airways Executive Club', 'http://www.britishairways.com/travel/forgottendetails/public/en_gb', '', 'https://www.britishairways.com/travel/execenrol/public/en_gb', 'OneWorld', '[{"at":"1","atn":"Avios"},{"at":"2","atn":"Tier Points"},{"at":"3","atn":"Eligible Flights"}]', '[{"ta":"1","tn":"Blue"},{"ta":"8","tn":"Bronze"},{"ta":"16","tn":"Silver"},{"ta":"24","tn":"Gold"}]', '["BA"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('BBL', 'Belavia Belarusian Airlines Belavia Leader', 'http://en.belavia.by/leader/', '', 'http://en.belavia.by/leader/registration/', 'Independent', '[{"at":"1","atn":"NonQualifying Points"},{"at":"2","atn":"Qualifying Points"},{"at":"3","atn":"Segments"}]', '[{"ta":"1","tn":"Classic"},{"ta":"8","tn":"Silver"},{"ta":"16","tn":"Golden"}]', '["B2"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('CCM', 'Copa Airlines ConnectMiles', 'https://connectmiles.copaair.com/en/enrollment#ForgetPassword', '', 'https://connectmiles.copaair.com/en/enrollment#DynamicEnrollment', 'StarAlliance', '[{"at":"1","atn":"Award Miles"},{"at":"2","atn":"Status Miles"},{"at":"3","atn":"Qualifying Segments"}]', '[{"ta":"1","tn":"Member"},{"ta":"8","tn":"Silver"},{"ta":"16","tn":"Gold"},{"ta":"24","tn":"Platinum"},{"ta":"32","tn":"Presidential Platinum"}]', '["CM","P5"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('CDF', 'China Airlines Dynasty Flyer', 'https://calec.china-airlines.com/dynasty-flyer/pwdqry.aspx', '', 'https://calec.china-airlines.com/dynasty-flyer/enroll.aspx', 'SkyTeam', '[{"at":"1","atn":"Miles"},{"at":"2","atn":"Status Miles"},{"at":"3","atn":"Status Segments"}]', '[{"ta":"1","tn":"Dynasty"},{"ta":"8","tn":"Gold"},{"ta":"16","tn":"Emerald"},{"ta":"24","tn":"Paragon"}]', '["AE","CI"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('CEM', 'China Eastern Eastern Miles', 'http://easternmiles.ceair.com/mpf/#/sign/forget', '', 'http://easternmiles.ceair.com/mpf/#/sign/register', 'SkyTeam', '[{"at":"1","atn":"Redeemable Points"},{"at":"2","atn":"Elite Qualification Points"},{"at":"3","atn":"Elite Qualification Segments"}]', '[{"ta":"1","tn":"Standard"},{"ta":"8","tn":"Silver"},{"ta":"16","tn":"Gold"},{"ta":"24","tn":"Platinum"}]', '["FM","MU"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('CXA', 'Cathay Pacific Marco Polo Club/AsiaMiles', 'https://www.asiamiles.com/am/en/account/forgotpin', '', 'https://www.asiamiles.com/am/en/about/join?WAright=JoinNow', 'OneWorld', '[{"at":"1","atn":"Asia Miles"},{"at":"4","atn":"Marco Polo Club Points"}]', '[{"ta":"1","tn":"Asia Miles Member"},{"ta":"8","tn":"Marco Polo Club Green"},{"ta":"16","tn":"Marco Polo Club Silver"},{"ta":"24","tn":"Marco Polo Club Gold"},{"ta":"32","tn":"Marco Polo Club Diamond"}]', '["CX","KA"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('DSM', 'Delta SkyMiles', 'https://www.delta.com/custlogin/validateUser.action?loginHelpPageName=forgotPassword', '', 'https://www.delta.com/profile/enrolllanding.action', 'SkyTeam', '[{"at":"1","atn":"Award Miles"},{"at":"2","atn":"Medallion Qualification Miles"},{"at":"3","atn":"Medallion Qualification Segments"},{"at":"5","atn":"Medallion Qualification Dollars"}]', '[{"ta":"1","tn":"Member"},{"ta":"8","tn":"Silver"},{"ta":"16","tn":"Gold"},{"ta":"24","tn":"Platinum"},{"ta":"32","tn":"Diamond"}]', '["DL"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('EAM', 'El Al Matmid', 'https://www.elal-matmid.com/en/Login/Pages/ForgotPassword.aspx', '', 'https://app.elal.co.il/clubs/registration/RegisterFlyer.aspx?lang=en&_ga=1.175121707.842894069.1475478030', 'Independent', '[{"at":"1","atn":"Award Points"},{"at":"2","atn":"Basic Points"},{"at":"3","atn":"Status segments"}]', '[{"ta":"1","tn":"Matmid"},{"ta":"8","tn":"Silver"},{"ta":"16","tn":"Gold"},{"ta":"24","tn":"Platinum"},{"ta":"32","tn":"Top Platinum"}]', '["LY"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('EKS', 'Emirates Skywards', 'https://www.emirates.com/account/us/english/login/forgot_membership_password.aspx', '', 'http://www.emirates.com/us/english/skywards/skywards_join_now/skywards_join_now_form.aspx', 'Independent', '[{"at":"1","atn":"Skywards Miles"},{"at":"2","atn":"Tier Miles"},{"at":"3","atn":"Qualifying Flights"}]', '[{"ta":"1","tn":"Blue"},{"ta":"8","tn":"Silver"},{"ta":"16","tn":"Gold"},{"ta":"24","tn":"Platinum"}]', '["EK"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('ETS', 'Ethiopian Airlines ShebaMiles', 'https://www.ethiopianairlines.com/AA/EN/shebamiles/forgot-pin', '', 'https://www.ethiopianairlines.com/AA/EN/shebamiles', 'StarAlliance', '[{"at":"1","atn":"Award Miles"},{"at":"2","atn":"Status Miles"},{"at":"3","atn":"Tier Qualifying Segments"}]', '[{"ta":"1","tn":"Member"},{"ta":"8","tn":"Blue"},{"ta":"16","tn":"Silver"},{"ta":"24","tn":"Gold"}]', '["3W","ET"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('EYG', 'Etihad Airways Guest', 'http://www.etihadguest.com/en/your-account/forgot-password/', '', 'https://www.etihadguest.com/en/join/', 'Independent', '[{"at":"1","atn":"Guest miles"},{"at":"2","atn":"Tier miles"},{"at":"3","atn":"Tier segments"}]', '[{"ta":"1","tn":"Etihad Guest"},{"ta":"8","tn":"Etihad Silver"},{"ta":"16","tn":"Etihad Gold"},{"ta":"24","tn":"Etihad Platinum"}]', '["EY"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('FPL', 'Finnair Plus', 'https://auth.finnair.com/cas/login;jsessionid=2C0DEAAF31F3098C3A70D66B56361905.cas2?execution=e1s1&_eventId=lostPassword&service=https://www.finnair.com/pl/AYPortal/wds/CASRedirect.action?SITE=FINRFINR&LANGUAGE=GB&COUNTRY_SITE=INT&PAGE=FPJO', '', 'http://www.finnair.com/INT/GB/join', 'OneWorld', '[{"at":"1","atn":"Award Points"},{"at":"2","atn":"Tier Points"},{"at":"3","atn":"Tier Flights"}]', '[{"ta":"1","tn":"Basic"},{"ta":"8","tn":"Silver"},{"ta":"16","tn":"Gold"},{"ta":"24","tn":"Platinum"},{"ta":"32","tn":"Lifetime Gold"},{"ta":"34","tn":"Lifetime Platinum"}]', '["AY"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('FWC', 'Hainan Airlines Fortune Wings Club', 'https://ffp.hnair.com/FFPCluben/GetPassword.aspx?', '', 'https://ffp.hnair.com/FFPCLUBEN/Front/FrameMain/member.aspx?type=0', 'Independent', '[{"at":"1","atn":"Base Points"},{"at":"2","atn":"Status Points"},{"at":"3","atn":"Base Segments"}]', '[{"ta":"1","tn":"Fortune Wings Card"},{"ta":"8","tn":"Select Card"},{"ta":"16","tn":"Silver Card"},{"ta":"24","tn":"Gold Card"},{"ta":"32","tn":"Platinum Card"}]', '["8L","CN","GS","HU","HX"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('GFF', 'GarudaMiles', 'https://garudamiles.com/TopHome/my-account/forget-password/', '', 'https://garudamiles.com/TopHome/enroll-now-lite/', 'SkyTeam', '[{"at":"1","atn":"Award miles"},{"at":"2","atn":"Tier miles"},{"at":"3","atn":"Flight Frequency"}]', '[{"ta":"1","tn":"Blue"},{"ta":"8","tn":"Silver"},{"ta":"16","tn":"Gold"},{"ta":"24","tn":"Platinum"}]', '["GA"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('GLP', 'Vietnam Airlines Lotusmiles', 'http://www.vietnamairlines.com/en/glp-online/forgot-password', '', 'http://www.vietnamairlines.com/en/glp-online/my-account/enrollment', 'SkyTeam', '[{"at":"1","atn":"Miles"},{"at":"2","atn":"Qualifying Miles"},{"at":"3","atn":"Qualifying Flights"}]', '[{"ta":"1","tn":"Registration"},{"ta":"8","tn":"Silver"},{"ta":"16","tn":"Titanium"},{"ta":"24","tn":"Gold"},{"ta":"32","tn":"Platinum"}]', '["VN"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('GOS', 'GOL Smiles', 'https://www.smiles.com.br/home#', '', 'https://www.smiles.com.br/cadastro', 'Independent', '[{"at":"1","atn":"Miles"},{"at":"2","atn":"Club Miles"}]', '[{"ta":"1","tn":"Smiles Member"},{"ta":"8","tn":"Prata"},{"ta":"16","tn":"Ouro"},{"ta":"24","tn":"Diamante"}]', '["G3"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('IBP', 'Iberia Plus', 'http://www.iberia.com/web/forgetPin.do', '', 'https://www.iberia.com/web/userRegistration.do?tabId=&menuId=WPVUEL', 'OneWorld', '[{"at":"1","atn":"Avios"},{"at":"2","atn":"Elite Points"},{"at":"3","atn":"Segments"}]', '[{"ta":"1","tn":"Classic (Clasica)"},{"ta":"8","tn":"Silver (Plata)"},{"ta":"16","tn":"Gold (Oro)"},{"ta":"24","tn":"Platinum (Platino)"}]', '["I2","IB"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('IFR', 'Air India Flying Returns', 'https://ffai.loyaltyplus.aero/ailoyalty/resetPassword.jsf', '', 'https://ffai.loyaltyplus.aero/ailoyalty/register.jsf?product=FFAI&lang=en', 'StarAlliance', '[{"at":"1","atn":"Miles"},{"at":"2","atn":"Status miles"}]', '[{"ta":"1","tn":"Flying Returns"},{"ta":"8","tn":"Silver Edge"},{"ta":"16","tn":"Gold Edge"},{"ta":"24","tn":"Maharajah Club"}]', '["AI"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('IML', 'EVA Air Inifinity MileageLands', 'https://eservice.evaair.com/flyeva/EVA/FFP/forgotten-password.aspx', '', 'https://eservice.evaair.com/flyeva/EVA/FFP/register-now.aspx', 'StarAlliance', '[{"at":"1","atn":"Miles"},{"at":"2","atn":"Status miles"},{"at":"3","atn":"Flight Sector"}]', '[{"ta":"1","tn":"Green"},{"ta":"8","tn":"Silver Card"},{"ta":"16","tn":"Gold Card"},{"ta":"24","tn":"Diamond Card"}]', '["B7","BR"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('JJP', 'Jet Airways JetPrivilege', 'https://www.jetprivilege.com/forgot-password', '', 'https://www.jetprivilege.com/rewards-program/enrol', 'Independent', '[{"at":"1","atn":"JPMiles"},{"at":"2","atn":"Tier JPMiles"},{"at":"3","atn":"Tier Points"}]', '[{"ta":"1","tn":"Blue"},{"ta":"8","tn":"Blue Plus"},{"ta":"16","tn":"Silver"},{"ta":"24","tn":"Gold"},{"ta":"32","tn":"Platinum"}]', '["9W","S2"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('JMB', 'JAL Mileage Bank', 'https://www121.jal.co.jp/JmbWeb/JR/PwdReqPre_en.do', '', 'https://www121.jal.co.jp/JmbWeb/JR/EnrollProposal_en.do', 'OneWorld', '[{"at":"1","atn":"Miles"},{"at":"2","atn":"FLY ON Points"},{"at":"3","atn":"Qualifying Flights"}]', '[{"ta":"1","tn":"Member"},{"ta":"8","tn":"JMB Crystal"},{"ta":"16","tn":"JMB Sapphire"},{"ta":"24","tn":"JGC Premier"},{"ta":"32","tn":"JMB Diamond"}]', '["JC","JL","NU"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('JTB', 'JetBlue TrueBlue', 'https://trueblue.jetblue.com/web/trueblue/forgot-password', '', 'https://trueblue.jetblue.com/web/trueblue/register', 'Independent', '[{"at":"1","atn":"TrueBlue Points"},{"at":"2","atn":"Base Flight Points"},{"at":"3","atn":"Flight Segment"}]', '[{"ta":"1","tn":"Member"},{"ta":"8","tn":"Mosaic"}]', '["B6"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('KOC', 'Kuwait Airways Oasis Club', 'https://oasisclub.kuwaitairways.com/home_pwd_forgotten.aspx?Active_Card_Number=', '', 'https://oasisclub.kuwaitairways.com/Join_now_personal.aspx', 'Independent', '[{"at":"1","atn":"Award Miles"},{"at":"2","atn":"Level Miles"},{"at":"3","atn":"Segments"}]', '[{"ta":"1","tn":"Oasis Blue"},{"ta":"8","tn":"Oasis Silver"},{"ta":"16","tn":"Oasis Gold"}]', '["KU"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('KSP', 'Korean Air Skypass', 'https://kr.koreanair.com/global/en/profile/account-recovery.html', '', 'https://kr.koreanair.com/global/en/profile/registration-page.html', 'SkyTeam', '[{"at":"1","atn":"Miles"},{"at":"2","atn":"Qualifying Miles"},{"at":"3","atn":"Qualifying Flights"}]', '[{"ta":"1","tn":"Skypass Club"},{"ta":"8","tn":"Morning Calm Club"},{"ta":"16","tn":"Morning Calm Premium Club"},{"ta":"24","tn":"Million Miler Club"}]', '["KE"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('LAP', 'LAN LATAM Pass', 'https://ssl.lan.com/cgi-bin/password_recovery/paso1.cgi', '', 'https://ssl.lan.com/cgi-bin/my_account/lp/register.cgi', 'OneWorld', '[{"at":"1","atn":"LANPASS KMS"},{"at":"2","atn":"LANPASS KMS Status"},{"at":"3","atn":"Segments"}]', '[{"ta":"1","tn":"LATAM"},{"ta":"8","tn":"Gold"},{"ta":"16","tn":"Platinum"},{"ta":"24","tn":"Black"},{"ta":"32","tn":"Black Signature"}]', '["4C","4M","LA","LP","LU","XL"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('LGC', 'Aer Lingus Gold Circle Club', 'https://www.aerlingus.com/html/register-profile.html#/?returnUrl=%2Fexperience-aer-lingus%2F', '', 'https://www.aerlingus.com/html/register-profile.html#/?returnUrl=%2Fexperience-aer-lingus%2F', 'Independent', '[{"at":"1","atn":"Points"},{"at":"2","atn":"Points"}]', '[{"ta":"1","tn":"Applicant"},{"ta":"8","tn":"Gold"},{"ta":"16","tn":"Prestige"},{"ta":"24","tn":"Elite"}]', '["EI"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('LMM', 'Lufthansa Miles & More', 'https://www.miles-and-more.com/online/portal/mam/de/account/forgotten_pin?l=en&cid=18002', '', 'https://www.miles-and-more.com/online/portal/mam/de/account/enrolment?l=en&cid=18002', 'StarAlliance', '[{"at":"1","atn":"Award Miles"},{"at":"2","atn":"Status Miles"},{"at":"3","atn":"Flight Segments"},{"at":"4","atn":"HON Circle Miles"}]', '[{"ta":"1","tn":"Member"},{"ta":"8","tn":"Frequent Traveller"},{"ta":"16","tn":"Senator"},{"ta":"24","tn":"HON Circle"}]', '["4U","DE","EN","EW","JP","LG","LH","LO","LX","OS","OU","SN"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('MAS', 'Turkish Airlines Miles&Smiles', 'https://www4.thy.com/tkmiles/pinproblems.tk?lang=en', '', 'https://www4.thy.com/tkmiles/membersignin.tk?lang=en', 'StarAlliance', '[{"at":"1","atn":"Redeemable Miles"},{"at":"2","atn":"Status miles"}]', '[{"ta":"1","tn":"Classic"},{"ta":"8","tn":"Classic Plus"},{"ta":"16","tn":"Elite"},{"ta":"24","tn":"Elite Plus"}]', '["TK"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('MCP', 'Aeromexico Club Premier', 'https://member.clubpremier.com/recuperar-password?lang=en', '', 'https://member.clubpremier.com/registro', 'SkyTeam', '[{"at":"1","atn":"Redeemable Points"},{"at":"2","atn":"Premier Points"}]', '[{"ta":"1","tn":"Classic (Clasico)"},{"ta":"8","tn":"Gold (Oro)"},{"ta":"16","tn":"Platinum (Platino)"},{"ta":"24","tn":"Titanium(Titanio)"}]', '["5D","AM"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('MEA', 'Middle East Airlines Cedar Miles', 'https://www.mea.com.lb/english/Cedar-Miles/Manage-My-Account?ID=60&lang=en', '', 'https://www.mea.com.lb/english/Cedar-Miles/Join-Now', 'SkyTeam', '[{"at":"1","atn":"Miles"},{"at":"2","atn":"Qualifying Miles"},{"at":"3","atn":"Qualifying Sectors"}]', '[{"ta":"1","tn":"Blue"},{"ta":"8","tn":"Silver"},{"ta":"16","tn":"Gold"},{"ta":"24","tn":"Platinum"}]', '["ME"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('MFE', 'Xiamen Airlines Egret Club', 'http://ffp.xiamenair.com/en-US/AccountSecurity/FindQueryPwd', '', 'http://ffp.xiamenair.com/en-US/member/register', 'SkyTeam', '[{"at":"1","atn":"Award Miles"},{"at":"2","atn":"Qualification Miles"},{"at":"3","atn":"Qualification Segments"}]', '[{"ta":"1","tn":"Member"},{"ta":"8","tn":"Silver"},{"ta":"16","tn":"Gold"}]', '["MF"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('MHE', 'Malaysia Airlines Enrich', 'https://www.enrich.malaysiaairlines.com/EnrichWebsite/forgotyourpassword', '', 'https://www.enrich.malaysiaairlines.com/EnrichWebsite/signup', 'OneWorld', '[{"at":"1","atn":"Enrich Miles"},{"at":"2","atn":"Elite Miles"},{"at":"3","atn":"Elite Sectors"}]', '[{"ta":"1","tn":"Blue"},{"ta":"8","tn":"Silver"},{"ta":"16","tn":"Gold"},{"ta":"24","tn":"Platinum"}]', '["FY","MH"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('MSP', 'EgyptAir Plus', 'http://www.egyptairplus.com/MS_Member_WebSite/frequent.jsp?code=RetrievePassword&lang=en', '', 'http://www.egyptairplus.com/MS_Member_WebSite/frequent.jsp?code=EnrollCheck&lang=en', 'StarAlliance', '[{"at":"1","atn":"Award Miles"},{"at":"2","atn":"Tier Miles"},{"at":"3","atn":"Tier Count"}]', '[{"ta":"1","tn":"Blue"},{"ta":"8","tn":"Silver"},{"ta":"16","tn":"Golden"},{"ta":"24","tn":"Platinum"}]', '["MS"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('NZA', 'Air New Zealand AirPoints', 'https://www.airnewzealand.co.nz/spr/challenge_phrase/challenge_phrase.jsp?formId=login_help&originateFrom=myKoru&currsite=www.airnz.co.nz', '', 'https://www.airnewzealand.co.nz/vloyalty/action/registration?option=default', 'StarAlliance', '[{"at":"1","atn":"Airpoints Dollars"},{"at":"2","atn":"Status Points"}]', '[{"ta":"1","tn":"Member"},{"ta":"8","tn":"Silver"},{"ta":"16","tn":"Gold"},{"ta":"24","tn":"Elite"}]', '["NZ"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('OKP', 'Czech Airlines OK Plus', 'https://www.csa.cz/en/ok_plus/okp_forgotten_pin.htm', '', 'https://www.csa.cz/en/ok_plus/okp_login_no_reg/okp_registration.htm', 'SkyTeam', '[{"at":"1","atn":"SkyTeam Reward Miles"},{"at":"2","atn":"SkyTeam Miles"},{"at":"3","atn":"SkyTeam Segments"}]', '[{"ta":"1","tn":"Member"},{"ta":"8","tn":"Silver"},{"ta":"16","tn":"Gold"},{"ta":"24","tn":"Platinum"}]', '["OK"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('PMM', 'Philippine Airlines Mabuhay Miles', 'https://www.mabuhaymiles.com/ForgotPassword', '', 'https://www.mabuhaymiles.com/Enrollment', 'Independent', '[{"at":"1","atn":"Mabuhay Miles"},{"at":"2","atn":"Tier Miles"},{"at":"3","atn":"Qualifying Flights"}]', '[{"ta":"1","tn":"Member"},{"ta":"8","tn":"Elite"},{"ta":"16","tn":"Premier Elite"},{"ta":"24","tn":"Million Miler"}]', '["2P","PR"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('QAP', 'Qatar Airways Privilege Club', 'https://qmiles.qatarairways.com/ffponline/ffp-online/forgotpassword.jsf', '', 'https://qmiles.qatarairways.com/ffponline/ffp-online/registration.jsf', 'OneWorld', '[{"at":"1","atn":"Qmiles"},{"at":"2","atn":"QPoints"}]', '[{"ta":"1","tn":"Burgundy"},{"ta":"8","tn":"Silver"},{"ta":"16","tn":"Gold"},{"ta":"24","tn":"Platinum"}]', '["QR"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('QFF', 'Qantas Frequent Flyer', 'http://www.qantas.com.au/fflyer/dyns/fpin', '', 'https://www.qantas.com.au/fflyer/dyns/joinff', 'OneWorld', '[{"at":"1","atn":"Qantas Points"},{"at":"2","atn":"Status Credits"}]', '[{"ta":"1","tn":"Bronze"},{"ta":"8","tn":"Silver"},{"ta":"16","tn":"Gold"},{"ta":"24","tn":"Platinum"},{"ta":"32","tn":"Platinum One"}]', '["JQ","QF"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('ROP', 'Thai Airways Royal Orchid Plus', 'http://www.thaiairways.com/en_TH/rop/Reset_Pin/Reset_Pin.page', '', 'http://www.thaiairways.com/app/rop/enroll/', 'StarAlliance', '[{"at":"1","atn":"Miles"},{"at":"2","atn":"Qualifying Miles"},{"at":"3","atn":"Qualifying Sector"},{"at":"4","atn":"Tier Miles"}]', '[{"ta":"1","tn":"Member"},{"ta":"8","tn":"Silver"},{"ta":"16","tn":"Gold"},{"ta":"24","tn":"Platinum"}]', '["TG","WE"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('SAF', 'SriLankan Airlines FlySmiLes', 'https://www.flysmiles.com/home/forgotten-password', '', 'https://www.flysmiles.com/home/register', 'OneWorld', '[{"at":"1","atn":"FlySmiLes Miles"},{"at":"2","atn":"Tier Miles"},{"at":"3","atn":"Flight Sectors"}]', '[{"ta":"1","tn":"Blue"},{"ta":"8","tn":"Classic"},{"ta":"16","tn":"Gold"},{"ta":"24","tn":"Platinum"}]', '["UL"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('SAV', 'South African Airways Voyager', 'https://www.flysaa.com/de/en/voyagerLogin.secured', '', 'https://www.flysaa.com/de/en/voyager!registration.action', 'StarAlliance', '[{"at":"1","atn":"Voyager Miles"},{"at":"2","atn":"Tier Miles"}]', '[{"ta":"1","tn":"Blue"},{"ta":"8","tn":"Silver"},{"ta":"16","tn":"Gold"},{"ta":"24","tn":"Platinum"},{"ta":"32","tn":"Lifetime Platinum"}]', '["4Z","SA"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('SEB', 'SAS EuroBonus', 'http://www.flysas.com/en/Generic/My_Profile/Forgotten-username-or-password/', '', 'http://www.flysas.com/en/eurobonus/create-account/', 'StarAlliance', '[{"at":"1","atn":"Basic Points"},{"at":"2","atn":"Status Points"},{"at":"3","atn":"Qualifying Flights"}]', '[{"ta":"1","tn":"Member"},{"ta":"8","tn":"Silver"},{"ta":"16","tn":"Gold"},{"ta":"24","tn":"Diamond"}]', '["SK","WF"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('SKF', 'Singapore Airlines KrisFlyer', 'https://www.singaporeair.com/kfResetPIN-flow.form?execution=e1s1', '', 'https://www.singaporeair.com/en_UK/ppsclub-krisflyer/registration-form/', 'StarAlliance', '[{"at":"1","atn":"Miles"},{"at":"2","atn":"Elite Miles"},{"at":"5","atn":"PPS Value"}]', '[{"ta":"1","tn":"Krisflyer"},{"ta":"8","tn":"Elite Silver"},{"ta":"16","tn":"Elite Gold"},{"ta":"24","tn":"PPS Club"},{"ta":"32","tn":"PPS Club Solitaire"}]', '["MI","SQ","TR","TZ"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('SPC', 'China Southern Sky Pearl Club', 'http://skypearl.csair.com/skypearl/skypearl/en/getAccountPassword.action?&NOSSL', '', 'http://skypearl.csair.com/skypearl/en/toQuickEnroll.action', 'SkyTeam', '[{"at":"1","atn":"Award Miles"},{"at":"2","atn":"Elite Qualifying Miles"},{"at":"3","atn":"Elite Qualifying Segments"}]', '[{"ta":"1","tn":"Base Member"},{"ta":"8","tn":"Silver"},{"ta":"16","tn":"Gold"}]', '["CZ"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('SPR', 'S7 Priority Club', 'https://www.s7.ru/home/personal_account/ffpforgotpassword.dot', '', 'https://www.s7.ru/home/personal_account/registration.dot', 'OneWorld', '[{"at":"1","atn":"Miles"},{"at":"2","atn":"Status Miles"},{"at":"3","atn":"Status Flights"}]', '[{"ta":"1","tn":"Classic"},{"ta":"8","tn":"Silver"},{"ta":"16","tn":"Gold"},{"ta":"24","tn":"Platinum"}]', '["S7"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('SVA', 'Saudi Arabian Airlines Alfursan', 'https://alfursan.saudiairlines.com/ForgotPassword.jsp', '', 'https://alfursan.saudiairlines.com/AlfursanSignUp.jsp', 'SkyTeam', '[{"at":"1","atn":"Reward Miles"},{"at":"2","atn":"Status Miles"},{"at":"3","atn":"International Sectors"}]', '[{"ta":"1","tn":"Blue"},{"ta":"8","tn":"Silver"},{"ta":"16","tn":"Gold"}]', '["SV"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('TMF', 'LATAM Fidelidade', 'http://www.tam.com.br/b2c/jsp/CarregaRecuperaDados.jhtml?hasTemplate=true', '', 'https://www.pontosmultiplus.com.br/cadastro/dados/?language=en', 'OneWorld', '[{"at":"1","atn":"Award Points"},{"at":"2","atn":"Status Points"},{"at":"3","atn":"Segments"}]', '[{"ta":"1","tn":"LATAM"},{"ta":"8","tn":"Gold"},{"ta":"16","tn":"Platinum"},{"ta":"24","tn":"Black"},{"ta":"32","tn":"Black Signature"}]', '["JJ","PZ"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('TPB', 'Air Berlin topbonus', 'https://www.airberlin.com/en-WW/site/yab/login/forgottenpw.php', '', 'https://topbonus.airberlin.com/web/tb/registration?lang=en&country=WW', 'OneWorld', '[{"at":"1","atn":"Award Miles"},{"at":"2","atn":"Status Miles"},{"at":"3","atn":"Status Segments"}]', '[{"ta":"1","tn":"Classic"},{"ta":"8","tn":"Silver"},{"ta":"16","tn":"Gold"},{"ta":"24","tn":"Platinum"}]', '["4T","AB","HG"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('TPV', 'TAP Victoria', 'https://wws.flytap.com/USA/enus/Victoria/forms/recover-pin', '', 'https://wws.flytap.com/Portugal/en/Victoria/forms/join-victoria', 'StarAlliance', '[{"at":"1","atn":"Bonus miles"},{"at":"2","atn":"Status miles"},{"at":"3","atn":"Status segments"}]', '[{"ta":"1","tn":"Miles"},{"ta":"8","tn":"Silver"},{"ta":"16","tn":"Gold"}]', '["TP"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('UMP', 'United Airlines MileagePlus', 'https://www.united.com/ual/en/us/account/security/passwordrecovery', '', 'https://www.united.com/ual/en/us/account/enroll/default', 'StarAlliance', '[{"at":"1","atn":"Award Miles"},{"at":"2","atn":"Premier Qualifying Miles"},{"at":"3","atn":"Premier Qualifying Segments"},{"at":"5","atn":"Premier Qualifying Dollars"}]', '[{"ta":"1","tn":"Member"},{"ta":"8","tn":"Premier Silver"},{"ta":"16","tn":"Premier Gold"},{"ta":"24","tn":"Premier Platinum"},{"ta":"32","tn":"Premier 1K"}]', '["UA"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('VAE', 'Virgin America Elevate', 'https://www.virginamerica.com/elevate-frequent-flyer', '', 'https://www.virginamerica.com/elevate-frequent-flyer/sign-up', 'Independent', '[{"at":"1","atn":"Reward Points"},{"at":"2","atn":"Status Points"},{"at":"3","atn":"Status Segments"}]', '[{"ta":"1","tn":"Red"},{"ta":"8","tn":"Silver"},{"ta":"16","tn":"Gold"}]', '["VX"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('VAV', 'Virgin Australia Velocity Frequent Flyer', 'https://www.velocityfrequentflyer.com/content/ResetPassword/', '', 'http://www.velocityfrequentflyer.com/content/Joinfree/', 'Independent', '[{"at":"1","atn":"Velocity Points"},{"at":"2","atn":"Status Credits"},{"at":"3","atn":"Eligible Sectors"}]', '[{"ta":"1","tn":"Red"},{"ta":"8","tn":"Silver"},{"ta":"16","tn":"Gold"},{"ta":"24","tn":"Platinum"}]', '["VA"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('VFC', 'Virgin Atlantic Flying Club', 'https://www.virgin-atlantic.com/en/us/frequentflyer/forgot_password_details.jsp', '', 'https://www.virgin-atlantic.com/en/us/frequentflyer/joinnow/index.jsp', 'Independent', '[{"at":"1","atn":"Miles"},{"at":"2","atn":"Tier Points"}]', '[{"ta":"1","tn":"Red"},{"ta":"8","tn":"Silver"},{"ta":"16","tn":"Gold"}]', '["VS"]');
INSERT INTO ffm_programs(program_code,program_name,help_url,web_site_url,signup_url,alliance,miles_type_configuration,tiers_configuration,airlines) VALUES ('WSR', 'WestJet Rewards', 'https://profile.westjet.com/guest/forgot.shtml', '', 'https://profile.westjet.com/guest/signUp.shtml?locale=en', 'Independent', '[{"at":"1","atn":"WestJet Dollars"},{"at":"2","atn":"Qualifying Flight Spend"}]', '[{"ta":"1","tn":"Teal"},{"ta":"8","tn":"Teal 1500"},{"ta":"16","tn":"Silver"},{"ta":"24","tn":"Gold"}]', '["WR","WS"]');
